import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import './globals.css';
import Toaster from '@/components/ui/sonner';
import { ourFileRouter } from '@/app/api/uploadthing/core';
import KakaoScript from '@/KakaoScript';

declare global {
  interface Window {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Kakao: any;
  }
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gila',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Toaster />
        {children}
      </body>
      <KakaoScript />
    </html>
  );
}
